/*
 * JSP generated by Resin Professional 4.0.44 (built Wed, 22 Apr 2015 02:04:40 PDT)
 */

package _jsp._netshop;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;
import java.sql.*;
import net.votes;

public class _vote__jsp extends com.caucho.jsp.JavaPage
{
  private static final java.util.HashMap<String,java.lang.reflect.Method> _jsp_functionMap = new java.util.HashMap<String,java.lang.reflect.Method>();
  private boolean _caucho_isDead;
  private boolean _caucho_isNotModified;
  private com.caucho.jsp.PageManager _jsp_pageManager;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.WebApp _jsp_application = _caucho_getApplication();
    com.caucho.jsp.PageContextImpl pageContext = _jsp_pageManager.allocatePageContext(this, _jsp_application, request, response, "/netshop/errorPage.jsp", session, 8192, true, false);

    TagState _jsp_state = null;

    try {
      _jspService(request, response, pageContext, _jsp_application, session, _jsp_state);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      _jsp_pageManager.freePageContext(pageContext);
    }
  }
  
  private void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response,
              com.caucho.jsp.PageContextImpl pageContext,
              javax.servlet.ServletContext application,
              javax.servlet.http.HttpSession session,
              TagState _jsp_state)
    throws Throwable
  {
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    final javax.el.ELContext _jsp_env = pageContext.getELContext();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    javax.servlet.jsp.tagext.JspTag _jsp_parent_tag = null;
    com.caucho.jsp.PageContextImpl _jsp_parentContext = pageContext;
    response.setContentType("text/html; charset=utf-8");

    out.write(_jsp_string0, 0, _jsp_string0.length);
    
String id = request.getParameter("id");
String type = request.getParameter("type");
double y = 0;
double n = 0;
double dy = 50;
double dn = 50;
if(id == null)
{
	out.print("id is null");
}
else
{
	votes votes = new votes();
	votes.setId(id);

		votes.execute(type);
	y =votes.getY();
	n =votes.getN();
	dy = y/(y+n)*100;
	dn = n/(y+n)*100;
}

    out.write(_jsp_string1, 0, _jsp_string1.length);
    out.print((id));
    out.write(_jsp_string2, 0, _jsp_string2.length);
    out.print((id));
    out.write(_jsp_string3, 0, _jsp_string3.length);
    out.print((id));
    out.write(_jsp_string4, 0, _jsp_string4.length);
    out.print((y));
    out.write(_jsp_string5, 0, _jsp_string5.length);
    out.print((n));
    out.write(_jsp_string6, 0, _jsp_string6.length);
  }

  private com.caucho.make.DependencyContainer _caucho_depends
    = new com.caucho.make.DependencyContainer();

  public java.util.ArrayList<com.caucho.vfs.Dependency> _caucho_getDependList()
  {
    return _caucho_depends.getDependencies();
  }

  public void _caucho_addDepend(com.caucho.vfs.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    _caucho_depends.add(depend);
  }

  protected void _caucho_setNeverModified(boolean isNotModified)
  {
    _caucho_isNotModified = true;
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;

    if (_caucho_isNotModified)
      return false;

    if (com.caucho.server.util.CauchoSystem.getVersionId() != -7371470110589488364L)
      return true;

    return _caucho_depends.isModified();
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
    TagState tagState;
  }

  public void init(com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.server.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("netshop/vote.jsp"), -1141387015393469140L, false);
    _caucho_depends.add(depend);
  }

  final static class TagState {

    void release()
    {
    }
  }

  public java.util.HashMap<String,java.lang.reflect.Method> _caucho_getFunctionMap()
  {
    return _jsp_functionMap;
  }

  public void caucho_init(ServletConfig config)
  {
    try {
      com.caucho.server.webapp.WebApp webApp
        = (com.caucho.server.webapp.WebApp) config.getServletContext();
      init(config);
      if (com.caucho.jsp.JspManager.getCheckInterval() >= 0)
        _caucho_depends.setCheckInterval(com.caucho.jsp.JspManager.getCheckInterval());
      _jsp_pageManager = webApp.getJspApplicationContext().getPageManager();
      com.caucho.jsp.TaglibManager manager = webApp.getJspApplicationContext().getTaglibManager();
      com.caucho.jsp.PageContextImpl pageContext = new com.caucho.jsp.InitPageContextImpl(webApp, this);
    } catch (Exception e) {
      throw com.caucho.config.ConfigException.create(e);
    }
  }

  private final static char []_jsp_string4;
  private final static char []_jsp_string6;
  private final static char []_jsp_string3;
  private final static char []_jsp_string0;
  private final static char []_jsp_string1;
  private final static char []_jsp_string2;
  private final static char []_jsp_string5;
  static {
    _jsp_string4 = "\u53f7\u6295\u7968\u5668',\r\n        x:'center'\r\n    },\r\n	    tooltip : {\r\n        trigger: 'item',\r\n        formatter: \"{a} <br/>{b} : {c} ({d}%)\"\r\n    },\r\n    series : [\r\n        {\r\n            name: '',\r\n            type: 'pie',\r\n            radius: '55%',\r\n            data:[\r\n                {value:".toCharArray();
    _jsp_string6 = " , name:'\u53cd\u5bf9'}\r\n            ]\r\n        }\r\n    ]\r\n};;\r\nif (option && typeof option === \"object\") {\r\n    myChart.setOption(option, true);\r\n}\r\n       </script>\r\n      \r\n</body>\r\n</html>".toCharArray();
    _jsp_string3 = "&type=no\">\r\n      <input type=\"submit\" name=\"button\" id=\"button\" value=\"\u53cd\u5bf9\">\r\n    </form></td>\r\n  </tr>\r\n</table>\r\n\r\n<script type=\"text/javascript\">\r\nvar dom = document.getElementById(\"container\");\r\nvar myChart = echarts.init(dom);var app = {};\r\noption = null;\r\noption = {\r\n	title : {\r\n        text: '".toCharArray();
    _jsp_string0 = "\r\n<script language=\"javascript\" src=\"/js/jquery-3.1.0.min.js\" charset=\"utf-8\"></script>\r\n<script language=\"javascript\" src=\"/js/echarts.min.js\" charset=\"utf-8\"></script>\r\n<html style=\"height: 100%\">\r\n   <head>\r\n       <meta charset=\"utf-8\">\r\n   </head>\r\n   ".toCharArray();
    _jsp_string1 = "\r\n<body style=\"height: 100%; margin: 0\">\r\n<div id=\"container\" style=\"height: 100%\"></div>\r\n<table width=\"200\" border=\"0\" align=\"center\">\r\n  <tr>\r\n    <td><form name=\"form1\" method=\"post\" action=\"vote.jsp?id=".toCharArray();
    _jsp_string2 = "&type=yes\">\r\n      <input type=\"submit\" name=\"button\" id=\"button\" value=\"\u8d5e\u6210\">\r\n    </form></td>\r\n    <td><form name=\"form1\" method=\"post\" action=\"vote.jsp?id=".toCharArray();
    _jsp_string5 = ", name:'\u8d5e\u540c'},\r\n                {value:".toCharArray();
  }
}
