/*
 * JSP generated by Resin Professional 4.0.44 (built Wed, 22 Apr 2015 02:04:40 PDT)
 */

package _jsp._netbbs;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;
import java.sql.*;
import java.util.*;
import org.hibernate.*;
import net.*;
import org.hibernate.cfg.Configuration;

public class _login__jsp extends com.caucho.jsp.JavaPage
{
  private static final java.util.HashMap<String,java.lang.reflect.Method> _jsp_functionMap = new java.util.HashMap<String,java.lang.reflect.Method>();
  private boolean _caucho_isDead;
  private boolean _caucho_isNotModified;
  private com.caucho.jsp.PageManager _jsp_pageManager;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.WebApp _jsp_application = _caucho_getApplication();
    com.caucho.jsp.PageContextImpl pageContext = _jsp_pageManager.allocatePageContext(this, _jsp_application, request, response, "/netbbs/errorPage.jsp", session, 8192, true, false);

    TagState _jsp_state = null;

    try {
      _jspService(request, response, pageContext, _jsp_application, session, _jsp_state);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      _jsp_pageManager.freePageContext(pageContext);
    }
  }
  
  private void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response,
              com.caucho.jsp.PageContextImpl pageContext,
              javax.servlet.ServletContext application,
              javax.servlet.http.HttpSession session,
              TagState _jsp_state)
    throws Throwable
  {
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    final javax.el.ELContext _jsp_env = pageContext.getELContext();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    javax.servlet.jsp.tagext.JspTag _jsp_parent_tag = null;
    com.caucho.jsp.PageContextImpl _jsp_parentContext = pageContext;
    response.setContentType("text/html; charset=utf-8");

    out.write(_jsp_string0, 0, _jsp_string0.length);
    
//HttpSession HSsession = request.getSession();
String rand = request.getParameter("text");//\u9a8c\u8bc1\u7801
if(rand!=null)//\u6709\u9a8c\u8bc1\u7801\u8bf4\u660e\u8981\u767b\u5f55
{
	if(!rand.equals(session.getAttribute("rand")))//\u9a8c\u8bc1\u7801\u8f93\u5165\u9519\u8bef
	{
		out.print("<script>alert(\"\u9a8c\u8bc1\u7801\u8f93\u5165\u9519\u8bef\uff01\");</script>");
	}	
	else
	{
		util sql = new util();
		sql.begin();
		Session hsession = sql.getSession(); //hibernate\u521d\u59cb\u5316
		hsession.beginTransaction();  
		String username = request.getParameter("username");//\u83b7\u53d6\u7528\u6237\u540d\u548c\u5bc6\u7801
		String password = request.getParameter("password");
		if(username.equals(""))//\u7a7a\u503c\u5224\u65ad   //\u5176\u5b9e\u53ef\u4ee5\u7528js\u6765\u5224\u65ad \u4f46\u662f\u6211\u90fd\u5199\u597d\u4e86 \u61d2\u5f97\u6539
		{
			out.print("<script>alert(\"\u8bf7\u8f93\u5165\u7528\u6237\u540d\uff01\");</script>");
			return;
		}
		if(password.equals(""))
		{
			out.print("<script>alert(\"\u8bf7\u8f93\u5165\u5bc6\u7801\uff01\");</script>");
			return;
		}
		List query= hsession.createSQLQuery("select * from user where username = '"+username+"' and password = '"+password+"' ").addEntity(user.class).list();;
		Iterator rs = query.iterator();//\u67e5\u8be2\u662f\u5426\u6709\u7b26\u5408\u7684
		if(rs.hasNext())
		{
			user nuser =(user)rs.next();      //\u6709\u7684\u8bdd \u5b58\u6570\u636e\u5230session
			login nlogin = new login();
			nlogin.setUsername(nuser.getUsername());
			nlogin.setId(nuser.getId());
			nlogin.setIslogin(true);
			session.setAttribute("login",nlogin); 
			out.print("<script>alert(\"\u6b22\u8fce\u56de\u6765,"+nuser.getUsername()+".\");location.href=\"index.html\";</script>");
		//	response.sendRedirect("index.jsp"); 
			return;
		}
		else
		{
			out.print("<script>alert(\"\u7528\u6237\u540d\u6216\u5bc6\u7801\u9519\u8bef\uff01\");</script>");
		}
		hsession.close();  
	}
	
}

login nlogin = (login)session.getAttribute("login");//\u5224\u65ad\u662f\u4e0d\u662f\u5728\u9017\u6211\u73a9
if(nlogin!=null && nlogin.isIslogin())
{
	out.print("<script>alert(\"\u4f60\u5df2\u767b\u5f55\uff01\");location.href=\"index.html\";</script>");
//	response.sendRedirect("index.jsp"); 
	return;
}


    out.write(_jsp_string1, 0, _jsp_string1.length);
  }

  private com.caucho.make.DependencyContainer _caucho_depends
    = new com.caucho.make.DependencyContainer();

  public java.util.ArrayList<com.caucho.vfs.Dependency> _caucho_getDependList()
  {
    return _caucho_depends.getDependencies();
  }

  public void _caucho_addDepend(com.caucho.vfs.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    _caucho_depends.add(depend);
  }

  protected void _caucho_setNeverModified(boolean isNotModified)
  {
    _caucho_isNotModified = true;
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;

    if (_caucho_isNotModified)
      return false;

    if (com.caucho.server.util.CauchoSystem.getVersionId() != -7371470110589488364L)
      return true;

    return _caucho_depends.isModified();
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
    TagState tagState;
  }

  public void init(com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.server.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("netbbs/login.jsp"), -8414594218183805564L, false);
    _caucho_depends.add(depend);
  }

  final static class TagState {

    void release()
    {
    }
  }

  public java.util.HashMap<String,java.lang.reflect.Method> _caucho_getFunctionMap()
  {
    return _jsp_functionMap;
  }

  public void caucho_init(ServletConfig config)
  {
    try {
      com.caucho.server.webapp.WebApp webApp
        = (com.caucho.server.webapp.WebApp) config.getServletContext();
      init(config);
      if (com.caucho.jsp.JspManager.getCheckInterval() >= 0)
        _caucho_depends.setCheckInterval(com.caucho.jsp.JspManager.getCheckInterval());
      _jsp_pageManager = webApp.getJspApplicationContext().getPageManager();
      com.caucho.jsp.TaglibManager manager = webApp.getJspApplicationContext().getTaglibManager();
      com.caucho.jsp.PageContextImpl pageContext = new com.caucho.jsp.InitPageContextImpl(webApp, this);
    } catch (Exception e) {
      throw com.caucho.config.ConfigException.create(e);
    }
  }

  private final static char []_jsp_string0;
  private final static char []_jsp_string1;
  static {
    _jsp_string0 = "\r\n<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n".toCharArray();
    _jsp_string1 = "\r\n<head>\r\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n<title>\u767b\u5f55</title>\r\n</head>\r\n<body>\r\n\r\n<form action=\"#\" method=\"post\">\r\n  \u7528\u6237\u540d\r\n  <input name=\"username\" id=\"username\"  type=\"text\" />\r\n  <p>\r\n    \u5bc6\u7801\r\n      <input type=\"password\" name=\"password\" id=\"password\" />\r\n  </p>\r\n  <p>\r\n    <input type=\"text\" name=\"text\" id=\"text\" />  <img src=\"../randCodeImage\" />\r\n  </p>\r\n  <p>\r\n    <input type=\"submit\" value=\"\u767b\u5f55\" />\r\n  </p>\r\n</form>\r\n</body>\r\n</html>".toCharArray();
  }
}
