/*
 * JSP generated by Resin Professional 4.0.44 (built Wed, 22 Apr 2015 02:04:40 PDT)
 */

package _jsp._netbbs;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;
import java.sql.*;
import java.util.*;
import java.text.*;
import java.math.*;
import org.hibernate.*;
import net.*;
import org.hibernate.cfg.Configuration;

public class _news_0control__jsp extends com.caucho.jsp.JavaPage
{
  private static final java.util.HashMap<String,java.lang.reflect.Method> _jsp_functionMap = new java.util.HashMap<String,java.lang.reflect.Method>();
  private boolean _caucho_isDead;
  private boolean _caucho_isNotModified;
  private com.caucho.jsp.PageManager _jsp_pageManager;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.WebApp _jsp_application = _caucho_getApplication();
    com.caucho.jsp.PageContextImpl pageContext = _jsp_pageManager.allocatePageContext(this, _jsp_application, request, response, "/netbbs/errorPage.jsp", session, 8192, true, false);

    TagState _jsp_state = null;

    try {
      _jspService(request, response, pageContext, _jsp_application, session, _jsp_state);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      _jsp_pageManager.freePageContext(pageContext);
    }
  }
  
  private void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response,
              com.caucho.jsp.PageContextImpl pageContext,
              javax.servlet.ServletContext application,
              javax.servlet.http.HttpSession session,
              TagState _jsp_state)
    throws Throwable
  {
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    final javax.el.ELContext _jsp_env = pageContext.getELContext();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    javax.servlet.jsp.tagext.JspTag _jsp_parent_tag = null;
    com.caucho.jsp.PageContextImpl _jsp_parentContext = pageContext;
    response.setContentType("text/html; charset=utf-8");

    out.write(_jsp_string0, 0, _jsp_string0.length);
    
util sql = new util();
sql.begin();
Session hsession = sql.getSession(); //hibernate\u521d\u59cb\u5316
hsession.beginTransaction();  

login nlogin = (login)session.getAttribute("login");//\u83b7\u53d6\u767b\u5f55\u72b6\u6001

String rand = request.getParameter("text");//\u9a8c\u8bc1\u7801
String text = request.getParameter("textarea");//\u5185\u5bb9
String title = request.getParameter("title");//\u6807\u9898

String pages = request.getParameter("page");//\u9875\u6570

String newsid = request.getParameter("newsid");//\u83b7\u53d6\u5220\u9664\u8bf7\u6c42
if(newsid != null)//\u5982\u679c\u8981\u5220\u9664
{
	List query2= hsession.createSQLQuery("select * from news where poid = "+nlogin.getId()+" and id ="+newsid).addEntity(news.class).list();//\u5224\u65ad\u6743\u9650 \u767b\u9646\u8005\u662f\u5426\u662f\u516c\u544a\u7684\u53d1\u5e03\u8005
	Iterator rs2 = query2.iterator();
	if(rs2.hasNext())//\u5982\u679c\u662f
	{
		news delnews =(news)rs2.next(); //\u83b7\u53d6\u5355\u8d34\u5b9e\u4f8b	
		hsession.delete(delnews);//\u5220\u9664 
		out.print("<script>alert(\"\u516c\u544a\u5df2\u5220\u9664!\");</script>");
 	 	hsession.getTransaction().commit();//\u63d0\u4ea4
	}
	else//\u5982\u679c\u4e0d\u662f
	{
		out.print("<script>alert(\"\u5220\u9664\u5931\u8d25!\u65e0\u6743\u9650\u6216\u516c\u544a\u4e0d\u5b58\u5728!\");</script>");
	}
}



if(rand!=null)//\u5982\u679c\u6709\u9a8c\u8bc1\u7801 \u8bf4\u660e\u7528\u6237\u8981\u53d1\u5e16
{
	if(!rand.equals(session.getAttribute("rand")))//\u9a8c\u8bc1\u7801\u8f93\u5165\u9519\u8bef
	{
		session.setAttribute("otext",text);
		session.setAttribute("otitle",title);
		out.print("<script>alert(\"\u9a8c\u8bc1\u7801\u8f93\u5165\u9519\u8bef\uff01\");</script>");
	}
	else
	{
		if(nlogin!=null && nlogin.isIslogin())//\u767b\u5f55\u4e86\u6ca1
		{
			news nnews = new news();//\u5e16\u5b50
			nnews.setMain(text);
			nnews.setPoid(nlogin.getId());//\u4e0a\u4f20\u8005ID
			nnews.setTitle(title);
			
			java.util.Date date= new java.util.Date();//\u521b\u5efa\u4e00\u4e2a\u65f6\u95f4\u5bf9\u8c61\uff0c\u83b7\u53d6\u5230\u5f53\u524d\u7684\u65f6\u95f4
			SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");//\u8bbe\u7f6e\u65f6\u95f4\u663e\u793a\u683c\u5f0f
			String nowtime = sdf.format(date);//\u5c06\u5f53\u524d\u65f6\u95f4\u683c\u5f0f\u5316\u4e3a\u5b57\u7b26
			
			nnews.setTime(nowtime);
			
			hsession.clear();
			hsession.save(nnews); 
			hsession.getTransaction().commit(); 
		} 
		else//\u6ca1\u767b\u5f55
		{
			out.print("<script>alert(\"\u4f60\u5c1a\u672a\u767b\u5f55\uff01\");location.href=\"login.jsp\";</script>");
			return;
		}
	}
}

String otext = (String)session.getAttribute("otext");//\u5b58\u5728session\u91cc\u7684\u8bb0\u5f55
String otitle = (String)session.getAttribute("otitle");
if(otext != null)//\u6709\u8bb0\u5f55\u5c31\u62ff\u51fa\u6765 \u6e05\u7a7asession
{
	session.removeAttribute("otext");
}
else
{
	otext = "";
}
if(otitle!=null)
{
	session.removeAttribute("otitle");
}
else
{
	otitle = "";
}

if(pages == null)//\u9ed8\u8ba4page1
{
	pages = "1";
}

int ipage = Integer.parseInt(pages);//string\u8f6cint
int limitnum = 10; 	//\u6301\u7eed\u51e0\u6761
int limit =(ipage-1)*limitnum; //\u4ece\u7b2c\u51e0\u6761\u5f00\u59cb

List query= hsession.createSQLQuery("select news.*,user.username from news,user WHERE news.poid = user.id order by news.time desc LIMIT "+limit+","+limitnum).list();//\u67e5\u8be2\u5e16\u5b50
Iterator rs = query.iterator();

    out.write(_jsp_string1, 0, _jsp_string1.length);
    
	if(nlogin!=null && nlogin.isIslogin())//\u6309\u7167\u662f\u5426\u767b\u5f55\u6765\u51b3\u5b9a\u8f93\u51fa\u5185\u5bb9
	{
		out.print("\u4f60\u597d,"+nlogin.getUsername());
		
	}
	else
	{
		out.print("<script>alert(\"\u4f60\u5c1a\u672a\u767b\u5f55\uff01\");location.href=\"index.html\";</script>");
	return;
	}
    
    out.write(_jsp_string2, 0, _jsp_string2.length);
    
	
	out.print("<a href=\"logout.jsp\">\u6ce8\u9500</a>");
	
	
	
    out.write(_jsp_string3, 0, _jsp_string3.length);
    
while(rs.hasNext())//\u83b7\u53d6\u5e16\u5b50\u67e5\u8be2\u7ed3\u679c
{
	Object[] rnews=(Object[])rs.next();//\u4f20\u503c\u7ed9\u53d8\u91cf
	int rnid=(int)rnews[0];//\u8fd4\u56de\u7684ID
    String rntitle=(String)rnews[1];
	String rntime=(String)rnews[3];
	String rnname=(String)rnews[5];
	
//post npost =(post)rs.next();      //\u53d8\u91cf\u8f93\u51fa
out.print("<tr><td  align=\"center\">"+rntime.substring(0,10)+"</td><td colspan=\"3\"><a href=\"post.jsp?id="+rnid+"\">");
out.print(rntitle);
out.print("</td><td align=\"right\">"+rnname+"<input type=\"button\" name=\"button\" id=\"button\" value=\"\u5220\u9664\"  onClick=\"delsubmit("+rnid+");\" /></td></tr>");
}
List query2= hsession.createSQLQuery("select count(id) as counts from news").list();//\u67e5\u8be2\u6240\u6709\u5e16\u5b50\u603b\u6570
Iterator rs2 = query2.iterator();
BigInteger postcounts=(BigInteger)rs2.next();
int ipostc = postcounts.intValue();//\u8f6c\u6210int
int maxpages = (ipostc/limitnum)+1;
out.print("<tr><td  align=\"center\" colspan=\"4\"><a href=\"index.jsp?page=1\">\u9996\u9875</a>&nbsp;");
if((ipage-1)>=1)
{
	out.print("<a href=\"index.jsp?page="+(ipage-1)+"\">\u4e0a\u4e00\u9875</a>&nbsp;");
}
for(int i = -3;i<=3;i++){ 
	if((ipage+i)>0 && (ipage+i)<=maxpages)//\u4e0d\u5982\u679c\u8d85\u51fa\u9875\u6570\u8303\u56f4
	{
		if(i==0)
		{
			out.print(ipage+"&nbsp;");
		}
		else
		{
			out.print("<a href=\"index.jsp?page="+(ipage+i)+"\">["+(ipage+i)+"]</a>&nbsp;");
		}
	}
}
if((ipage+1)<=maxpages)
{
	out.print("<a href=\"index.jsp?page="+(ipage+1)+"\">\u4e0b\u4e00\u9875</a>&nbsp;");
}
out.print("<a href=\"index.jsp?page="+maxpages+"\">\u672b\u9875</a></td></tr>");
hsession.close();  //\u4e0d\u52a0\u8fd9\u4e2a\u670d\u52a1\u5668\u5185\u5b58\u4f1a\u7206

    out.write(_jsp_string4, 0, _jsp_string4.length);
    out.print((otitle));
    out.write(_jsp_string5, 0, _jsp_string5.length);
    out.print((otext));
    out.write(_jsp_string6, 0, _jsp_string6.length);
  }

  private com.caucho.make.DependencyContainer _caucho_depends
    = new com.caucho.make.DependencyContainer();

  public java.util.ArrayList<com.caucho.vfs.Dependency> _caucho_getDependList()
  {
    return _caucho_depends.getDependencies();
  }

  public void _caucho_addDepend(com.caucho.vfs.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    _caucho_depends.add(depend);
  }

  protected void _caucho_setNeverModified(boolean isNotModified)
  {
    _caucho_isNotModified = true;
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;

    if (_caucho_isNotModified)
      return false;

    if (com.caucho.server.util.CauchoSystem.getVersionId() != -7371470110589488364L)
      return true;

    return _caucho_depends.isModified();
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
    TagState tagState;
  }

  public void init(com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.server.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("netbbs/news_control.jsp"), 3693719127343339478L, false);
    _caucho_depends.add(depend);
  }

  final static class TagState {

    void release()
    {
    }
  }

  public java.util.HashMap<String,java.lang.reflect.Method> _caucho_getFunctionMap()
  {
    return _jsp_functionMap;
  }

  public void caucho_init(ServletConfig config)
  {
    try {
      com.caucho.server.webapp.WebApp webApp
        = (com.caucho.server.webapp.WebApp) config.getServletContext();
      init(config);
      if (com.caucho.jsp.JspManager.getCheckInterval() >= 0)
        _caucho_depends.setCheckInterval(com.caucho.jsp.JspManager.getCheckInterval());
      _jsp_pageManager = webApp.getJspApplicationContext().getPageManager();
      com.caucho.jsp.TaglibManager manager = webApp.getJspApplicationContext().getTaglibManager();
      com.caucho.jsp.PageContextImpl pageContext = new com.caucho.jsp.InitPageContextImpl(webApp, this);
    } catch (Exception e) {
      throw com.caucho.config.ConfigException.create(e);
    }
  }

  private final static char []_jsp_string4;
  private final static char []_jsp_string3;
  private final static char []_jsp_string5;
  private final static char []_jsp_string6;
  private final static char []_jsp_string2;
  private final static char []_jsp_string0;
  private final static char []_jsp_string1;
  static {
    _jsp_string4 = "\r\n  <form action=\"#\" method=\"post\" name=\"form1\" id=\"form1\">\r\n    <tr>\r\n      <td colspan=\"4\"> \u6807\u9898\r\n      <input type=\"text\" name=\"title\" id=\"title\" value=\"".toCharArray();
    _jsp_string3 = "</td>\r\n    <td width=\"35\" align=\"right\" valign=\"middle\"><a href=\"register.jsp\">\u6ce8\u518c</a></td>\r\n  </tr>\r\n  ".toCharArray();
    _jsp_string5 = "\"  />\r\n  </td>\r\n  <tr><td colspan=\"4\">\r\n    <textarea name=\"textarea\" id=\"textarea\" cols=\"45\" rows=\"5\" >".toCharArray();
    _jsp_string6 = "</textarea>\r\n </td> </tr><tr>\r\n <td width=\"90\" align=\"right\">\r\n    <p>\r\n        <input type=\"submit\" name=\"button\" id=\"button\" value=\"\u53d1\u8868\" />\r\n      </p></td>\r\n      <td colspan=\"2\" align=\"right\"><input type=\"text\" name=\"text\" id=\"text\" /></td>\r\n      <td><img src=\"../randCodeImage\" /></td>\r\n    </tr>\r\n  </form>\r\n</table>\r\n</body>\r\n</html>".toCharArray();
    _jsp_string2 = "</td>\r\n    <td width=\"224\" align=\"right\" valign=\"middle\"></td>\r\n    <td width=\"87\" align=\"right\" valign=\"middle\">".toCharArray();
    _jsp_string0 = "\r\n<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n<head>\r\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n<title>news</title>\r\n</head>\r\n".toCharArray();
    _jsp_string1 = "\r\n<body>\r\n<form id=\"form1\" name=\"form2\" method=\"post\" action=\"#\">\r\n	<input name=\"newsid\" id=\"newsid\" type=\"hidden\" value=\"\" />\r\n</form>\r\n<script type=\"text/javascript\">  //\u5904\u7406\u5220\u9664\u7684\u786e\u8ba4\r\nfunction delsubmit(newsid) {  \r\n    var result = confirm(\"\u662f\u5426\u5220\u9664\u6b64\u8d34?\");  \r\n    if (result == true) {  \r\n    //    alert(\"\u5e16\u5b50\u5df2\u5220\u9664.\"); \r\n		document.getElementById('newsid').value =newsid;\r\n		document.form2.submit();\r\n    }\r\n}  \r\n</script>  \r\n<table width=\"626\" height=\"57\" border=\"0\" align=\"center\">\r\n  <tr>\r\n    <td align=\"left\" valign=\"middle\" colspan=\"3\">\r\n	".toCharArray();
  }
}
