/*
 * JSP generated by Resin Professional 4.0.44 (built Wed, 22 Apr 2015 02:04:40 PDT)
 */

package _jsp._netbbs;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;
import java.sql.*;
import java.util.*;
import java.text.*;
import java.math.*;
import org.hibernate.*;
import net.*;
import org.hibernate.cfg.Configuration;

public class _news__jsp extends com.caucho.jsp.JavaPage
{
  private static final java.util.HashMap<String,java.lang.reflect.Method> _jsp_functionMap = new java.util.HashMap<String,java.lang.reflect.Method>();
  private boolean _caucho_isDead;
  private boolean _caucho_isNotModified;
  private com.caucho.jsp.PageManager _jsp_pageManager;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.WebApp _jsp_application = _caucho_getApplication();
    com.caucho.jsp.PageContextImpl pageContext = _jsp_pageManager.allocatePageContext(this, _jsp_application, request, response, "/netbbs/errorPage.jsp", session, 8192, true, false);

    TagState _jsp_state = null;

    try {
      _jspService(request, response, pageContext, _jsp_application, session, _jsp_state);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      _jsp_pageManager.freePageContext(pageContext);
    }
  }
  
  private void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response,
              com.caucho.jsp.PageContextImpl pageContext,
              javax.servlet.ServletContext application,
              javax.servlet.http.HttpSession session,
              TagState _jsp_state)
    throws Throwable
  {
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    final javax.el.ELContext _jsp_env = pageContext.getELContext();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    javax.servlet.jsp.tagext.JspTag _jsp_parent_tag = null;
    com.caucho.jsp.PageContextImpl _jsp_parentContext = pageContext;
    response.setContentType("text/html; charset=utf-8");

    out.write(_jsp_string0, 0, _jsp_string0.length);
    
util sql = new util();
sql.begin();
Session hsession = sql.getSession(); //hibernate\u521d\u59cb\u5316
hsession.beginTransaction();  

String newsid = request.getParameter("id");//ID
if(newsid == null)//\u5982\u679c\u6ca1\u6709\u516c\u544aID
{
	out.print("<script>alert(\"\u516c\u544a\u4e0d\u5b58\u5728\uff01\");location.href=\"index.html\";</script>");
//	response.sendRedirect("index.jsp"); 
	return;
}
List query= hsession.createSQLQuery("select news.time,news.title,news.main,user.username from news,user where news.poid=user.id and news.id ="+newsid).list();
Iterator rs = query.iterator();
String rntime;
String rntitle;
String rnmain;
String rnname;
if(rs.hasNext())//\u67e5\u8be2\u7ed3\u679c
{
	Object[] rnews=(Object[])rs.next();//\u4f20\u503c\u7ed9\u53d8\u91cf
	rntime=(String)rnews[0];
	rntitle=(String)rnews[1];
	rnmain=(String)rnews[2];
	rnname=(String)rnews[3];

}
else
{
	out.print("<script>alert(\"\u516c\u544a\u4e0d\u5b58\u5728\uff01\");location.href=\"index.html\";</script>");
//	response.sendRedirect("index.jsp"); 
	return;
}

    out.write(_jsp_string1, 0, _jsp_string1.length);
    out.print((rntitle));
    out.write(_jsp_string2, 0, _jsp_string2.length);
    out.print((rntime));
    out.write(_jsp_string3, 0, _jsp_string3.length);
    out.print((rnname));
    out.write(_jsp_string4, 0, _jsp_string4.length);
    out.print((rnmain));
    out.write(_jsp_string5, 0, _jsp_string5.length);
  }

  private com.caucho.make.DependencyContainer _caucho_depends
    = new com.caucho.make.DependencyContainer();

  public java.util.ArrayList<com.caucho.vfs.Dependency> _caucho_getDependList()
  {
    return _caucho_depends.getDependencies();
  }

  public void _caucho_addDepend(com.caucho.vfs.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    _caucho_depends.add(depend);
  }

  protected void _caucho_setNeverModified(boolean isNotModified)
  {
    _caucho_isNotModified = true;
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;

    if (_caucho_isNotModified)
      return false;

    if (com.caucho.server.util.CauchoSystem.getVersionId() != -7371470110589488364L)
      return true;

    return _caucho_depends.isModified();
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
    TagState tagState;
  }

  public void init(com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.server.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("netbbs/news.jsp"), -118880711313367374L, false);
    _caucho_depends.add(depend);
  }

  final static class TagState {

    void release()
    {
    }
  }

  public java.util.HashMap<String,java.lang.reflect.Method> _caucho_getFunctionMap()
  {
    return _jsp_functionMap;
  }

  public void caucho_init(ServletConfig config)
  {
    try {
      com.caucho.server.webapp.WebApp webApp
        = (com.caucho.server.webapp.WebApp) config.getServletContext();
      init(config);
      if (com.caucho.jsp.JspManager.getCheckInterval() >= 0)
        _caucho_depends.setCheckInterval(com.caucho.jsp.JspManager.getCheckInterval());
      _jsp_pageManager = webApp.getJspApplicationContext().getPageManager();
      com.caucho.jsp.TaglibManager manager = webApp.getJspApplicationContext().getTaglibManager();
      com.caucho.jsp.PageContextImpl pageContext = new com.caucho.jsp.InitPageContextImpl(webApp, this);
    } catch (Exception e) {
      throw com.caucho.config.ConfigException.create(e);
    }
  }

  private final static char []_jsp_string1;
  private final static char []_jsp_string3;
  private final static char []_jsp_string5;
  private final static char []_jsp_string2;
  private final static char []_jsp_string4;
  private final static char []_jsp_string0;
  static {
    _jsp_string1 = "\r\n<body>\r\n<table width=\"912\" height=\"606\" border=\"1\">\r\n  <tr>\r\n    <td height=\"23\" align=\"center\">&nbsp;</td>\r\n  </tr>\r\n   <tr>\r\n    <td height=\"60\" align=\"center\"><strong>".toCharArray();
    _jsp_string3 = "</td>\r\n  </tr>\r\n  <tr>\r\n    <td height=\"28\" align=\"center\">".toCharArray();
    _jsp_string5 = "</td>\r\n  </tr>\r\n</table>\r\n</body>\r\n</html>".toCharArray();
    _jsp_string2 = "</strong></td>\r\n  </tr>\r\n  <tr>\r\n    <td height=\"31\" align=\"center\">".toCharArray();
    _jsp_string4 = "</td>\r\n  </tr>\r\n   <tr>\r\n    <td height=\"450\" align=\"left\" valign=\"top\">".toCharArray();
    _jsp_string0 = "\r\n<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n<head>\r\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n<title>news</title>\r\n</head>\r\n".toCharArray();
  }
}
