/*
 * JSP generated by Resin Professional 4.0.44 (built Wed, 22 Apr 2015 02:04:40 PDT)
 */

package _jsp._netbbs;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;
import java.sql.*;
import java.util.*;
import java.text.*;
import org.hibernate.*;
import net.*;
import org.hibernate.cfg.Configuration;

public class _register__jsp extends com.caucho.jsp.JavaPage
{
  private static final java.util.HashMap<String,java.lang.reflect.Method> _jsp_functionMap = new java.util.HashMap<String,java.lang.reflect.Method>();
  private boolean _caucho_isDead;
  private boolean _caucho_isNotModified;
  private com.caucho.jsp.PageManager _jsp_pageManager;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.WebApp _jsp_application = _caucho_getApplication();
    com.caucho.jsp.PageContextImpl pageContext = _jsp_pageManager.allocatePageContext(this, _jsp_application, request, response, "/netbbs/errorPage.jsp", session, 8192, true, false);

    TagState _jsp_state = null;

    try {
      _jspService(request, response, pageContext, _jsp_application, session, _jsp_state);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      _jsp_pageManager.freePageContext(pageContext);
    }
  }
  
  private void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response,
              com.caucho.jsp.PageContextImpl pageContext,
              javax.servlet.ServletContext application,
              javax.servlet.http.HttpSession session,
              TagState _jsp_state)
    throws Throwable
  {
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    final javax.el.ELContext _jsp_env = pageContext.getELContext();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    javax.servlet.jsp.tagext.JspTag _jsp_parent_tag = null;
    com.caucho.jsp.PageContextImpl _jsp_parentContext = pageContext;
    response.setContentType("text/html; charset=utf-8");

    out.write(_jsp_string0, 0, _jsp_string0.length);
    
String rand = request.getParameter("rand");//\u9a8c\u8bc1\u7801
if(rand!=null)
{
	if(!rand.equals(session.getAttribute("rand")))//\u9a8c\u8bc1\u7801\u8f93\u5165\u9519\u8bef
	{
		out.print("<script>alert(\"\u9a8c\u8bc1\u7801\u8f93\u5165\u9519\u8bef\uff01\");</script>");
	}	
	else
	{
		String username = request.getParameter("username");//\u83b7\u53d6\u63d0\u4ea4\u6570\u636e
		String password = request.getParameter("password");
		String password2 = request.getParameter("password2");
		if(!username.equals(""))//\u7a7a\u503c\u5224\u65ad   
		{
			if(!password.equals(""))//\u5176\u5b9e\u53ef\u4ee5\u7528JS\u505a \u4f46\u662f\u6211\u90fd\u5199\u597d\u4e86 
			{
				if(password.equals(password2))
				{
					util sql = new util();
					sql.begin();
					Session hsession = sql.getSession(); //hibernate\u521d\u59cb\u5316
					hsession.beginTransaction();  
					List query= hsession.createSQLQuery("select * from user where username = '"+username+"'").addEntity(user.class).list();;
					Iterator rs = query.iterator();
					
					java.util.Date date= new java.util.Date();//\u521b\u5efa\u4e00\u4e2a\u65f6\u95f4\u5bf9\u8c61\uff0c\u83b7\u53d6\u5230\u5f53\u524d\u7684\u65f6\u95f4
					SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");//\u8bbe\u7f6e\u65f6\u95f4\u663e\u793a\u683c\u5f0f
					String nowtime = sdf.format(date);//\u5c06\u5f53\u524d\u65f6\u95f4\u683c\u5f0f\u5316\u4e3a\u5b57\u7b26\u4e32
					
					if(!rs.hasNext())
					{
						user newuser = new user();  
						newuser.setTime(nowtime);//\u6ce8\u518c\u65f6\u95f4
						newuser.setUsername(username);
						newuser.setPassword(password);
						newuser.setIcon("");//\u5934\u50cf  
						newuser.setPoint(0);//\u79ef\u5206 //\u597d\u50cf\u6682\u65f6\u7528\u4e0d\u5230
						hsession.save(newuser); 
						hsession.getTransaction().commit();   
						hsession.close(); 
						out.print("<script>alert(\"\u6ce8\u518c\u6210\u529f!\");location.href=\"login.jsp\";</script>");
					}
					else
					{
						out.print("<script>alert(\"\u7528\u6237\u540d\u5df2\u5b58\u5728\uff01\");</script>");
						hsession.close(); 
					}
				}
				else
				{
					out.print("<script>alert(\"\u5bc6\u7801\u8f93\u5165\u4e0d\u4e00\u81f4\uff01\");</script>");
				}
			}
			else
			{
				out.print("<script>alert(\"\u8bf7\u8f93\u5165\u5bc6\u7801\uff01\");</script>");
			}
		}
		else
		{
			out.print("<script>alert(\"\u8bf7\u8f93\u5165\u7528\u6237\u540d\uff01\");</script>");
		}
		
	}
}

    out.write(_jsp_string1, 0, _jsp_string1.length);
  }

  private com.caucho.make.DependencyContainer _caucho_depends
    = new com.caucho.make.DependencyContainer();

  public java.util.ArrayList<com.caucho.vfs.Dependency> _caucho_getDependList()
  {
    return _caucho_depends.getDependencies();
  }

  public void _caucho_addDepend(com.caucho.vfs.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    _caucho_depends.add(depend);
  }

  protected void _caucho_setNeverModified(boolean isNotModified)
  {
    _caucho_isNotModified = true;
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;

    if (_caucho_isNotModified)
      return false;

    if (com.caucho.server.util.CauchoSystem.getVersionId() != -7371470110589488364L)
      return true;

    return _caucho_depends.isModified();
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
    TagState tagState;
  }

  public void init(com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.server.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("netbbs/register.jsp"), 2419492958565684530L, false);
    _caucho_depends.add(depend);
  }

  final static class TagState {

    void release()
    {
    }
  }

  public java.util.HashMap<String,java.lang.reflect.Method> _caucho_getFunctionMap()
  {
    return _jsp_functionMap;
  }

  public void caucho_init(ServletConfig config)
  {
    try {
      com.caucho.server.webapp.WebApp webApp
        = (com.caucho.server.webapp.WebApp) config.getServletContext();
      init(config);
      if (com.caucho.jsp.JspManager.getCheckInterval() >= 0)
        _caucho_depends.setCheckInterval(com.caucho.jsp.JspManager.getCheckInterval());
      _jsp_pageManager = webApp.getJspApplicationContext().getPageManager();
      com.caucho.jsp.TaglibManager manager = webApp.getJspApplicationContext().getTaglibManager();
      com.caucho.jsp.PageContextImpl pageContext = new com.caucho.jsp.InitPageContextImpl(webApp, this);
    } catch (Exception e) {
      throw com.caucho.config.ConfigException.create(e);
    }
  }

  private final static char []_jsp_string1;
  private final static char []_jsp_string0;
  static {
    _jsp_string1 = "\r\n<body>\r\n<form action=\"#\" method=\"post\">\r\n<table width=\"446\" border=\"0\">\r\n  <tr>\r\n    <td width=\"76\">\u7528\u6237\u540d</td>\r\n    <td width=\"168\"><input type=\"text\" name=\"username\" id=\"username\" /></td>\r\n  </tr>\r\n  <tr>\r\n    <td>\u5bc6\u7801</td>\r\n    <td><input name=\"password\" type=\"password\" id=\"password\" /></td>\r\n  </tr>\r\n    <tr>\r\n    <td>\u786e\u8ba4\u5bc6\u7801</td>\r\n    <td><input type=\"password\" name=\"password2\" id=\"password2\" /></td>\r\n  </tr>\r\n    <tr>\r\n    <td>\u9a8c\u8bc1\u7801</td>\r\n    <td><input type=\"text\" name=\"rand\" id=\"rand\" /></td>\r\n    <td width=\"188\"><img src=\"../randCodeImage\" /></td>\r\n  </tr>\r\n    <tr>\r\n    <td>&nbsp;</td>\r\n    <td><input type=\"submit\" name=\"button\" id=\"button\" value=\"\u6ce8\u518c\" /></td>\r\n  </tr>\r\n</table>\r\n</form>\r\n</body>\r\n</html>".toCharArray();
    _jsp_string0 = "\r\n<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n<head>\r\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n<title>\u6ce8\u518c</title>\r\n</head>\r\n".toCharArray();
  }
}
